import { mauiZones } from "@/lib/mauiZones";
import { createOfficialMauiFads, fadsSourceTimestamp } from "@/lib/sources/fads";
import { hawaiiWeatherTodaySourceTimestamp } from "@/lib/sources/hawaiiWeatherToday";
import { ndbcSourceTimestamp } from "@/lib/sources/ndbc";
import { noaaMarineTextSourceTimestamp } from "@/lib/sources/noaaMarineText";
import { noaaTidesSourceTimestamp } from "@/lib/sources/noaaTides";
import { nwsSourceTimestamp } from "@/lib/sources/nws";
import { nwsSurfSourceTimestamp } from "@/lib/sources/nwsSurf";
import { pacioosSourceTimestamp } from "@/lib/sources/pacioos";
import { windytronSourceTimestamp } from "@/lib/sources/windytron";
import type { BuoyObservation, HarborWindObservation, MarineForecast, MarineWarning, MauiDailyReport, SurfForecast, TideEvent } from "@/lib/types";

const issuedAt = "2026-05-18T06:00:00-10:00";

const mockForecasts: MarineForecast[] = [
  {
    zoneId: "north-shore-maliko",
    period: "Today",
    windDirection: "ENE",
    windSpeedKt: 22,
    gustKt: 31,
    seasFt: 6,
    swellFt: 4,
    swellDirection: "E/NE trade swell",
    swellPeriodSec: 10,
    rainChancePercent: 28,
    clouds: "partly",
    advisory: "Trades building by midday",
    summary: "Maliko Harbor launch area forecast data.",
    source: "Mock blend: NWS hourly, NOAA CWF, MFM",
    issuedAt,
  },
  {
    zoneId: "north-shore-maliko",
    period: "Tomorrow",
    windDirection: "ENE",
    windSpeedKt: 24,
    gustKt: 34,
    seasFt: 7,
    swellFt: 5,
    swellDirection: "E/NE trade swell",
    swellPeriodSec: 9,
    rainChancePercent: 38,
    clouds: "mostly",
    advisory: "Stronger trades",
    summary: "Maliko Harbor launch area forecast data.",
    source: "Mock blend: NWS hourly, NOAA CWF, MFM",
    issuedAt,
  },
  {
    zoneId: "north-shore-maliko",
    period: "Day 3",
    windDirection: "E",
    windSpeedKt: 18,
    gustKt: 26,
    seasFt: 5,
    swellFt: 4,
    swellDirection: "E trade swell",
    swellPeriodSec: 10,
    rainChancePercent: 24,
    clouds: "partly",
    summary: "Maliko Harbor launch area forecast data.",
    source: "Mock blend: NWS hourly, NOAA CWF, MFM",
    issuedAt,
  },
  {
    zoneId: "south-shore-kihei-maalaea",
    period: "Today",
    windDirection: "NE",
    windSpeedKt: 13,
    gustKt: 20,
    seasFt: 3,
    swellFt: 2,
    swellDirection: "S/SSW",
    swellPeriodSec: 12,
    rainChancePercent: 18,
    clouds: "few",
    summary: "South Shore / Kihei / Maalaea forecast data.",
    source: "Mock blend: NWS hourly, NOAA CWF, MFM",
    issuedAt,
  },
  {
    zoneId: "south-shore-kihei-maalaea",
    period: "Tomorrow",
    windDirection: "NE",
    windSpeedKt: 16,
    gustKt: 24,
    seasFt: 4,
    swellFt: 3,
    swellDirection: "SSW",
    swellPeriodSec: 14,
    rainChancePercent: 22,
    clouds: "partly",
    summary: "South Shore / Kihei / Maalaea forecast data.",
    source: "Mock blend: NWS hourly, NOAA CWF, MFM",
    issuedAt,
  },
  {
    zoneId: "south-shore-kihei-maalaea",
    period: "Day 3",
    windDirection: "ENE",
    windSpeedKt: 12,
    gustKt: 18,
    seasFt: 3,
    swellFt: 3,
    swellDirection: "S",
    swellPeriodSec: 15,
    rainChancePercent: 18,
    clouds: "few",
    summary: "South Shore / Kihei / Maalaea forecast data.",
    source: "Mock blend: NWS hourly, NOAA CWF, MFM",
    issuedAt,
  },
  {
    zoneId: "west-maui",
    period: "Today",
    windDirection: "NE",
    windSpeedKt: 11,
    gustKt: 17,
    seasFt: 3,
    swellFt: 2,
    swellDirection: "NNW wrap",
    swellPeriodSec: 13,
    rainChancePercent: 15,
    clouds: "few",
    summary: "Leeward pockets start clean, with afternoon texture near exposed points.",
    source: "Mock blend: NWS hourly, NOAA CWF, MFM",
    issuedAt,
  },
  {
    zoneId: "west-maui",
    period: "Tomorrow",
    windDirection: "NE",
    windSpeedKt: 13,
    gustKt: 21,
    seasFt: 3,
    swellFt: 2,
    swellDirection: "NNW wrap",
    swellPeriodSec: 12,
    rainChancePercent: 18,
    clouds: "few",
    summary: "West Maui forecast data.",
    source: "Mock blend: NWS hourly, NOAA CWF, MFM",
    issuedAt,
  },
  {
    zoneId: "west-maui",
    period: "Day 3",
    windDirection: "ENE",
    windSpeedKt: 10,
    gustKt: 16,
    seasFt: 2,
    swellFt: 2,
    swellDirection: "S wrap",
    swellPeriodSec: 14,
    rainChancePercent: 15,
    clouds: "few",
    summary: "West Maui forecast data.",
    source: "Mock blend: NWS hourly, NOAA CWF, MFM",
    issuedAt,
  },
  {
    zoneId: "windward-hana",
    period: "Today",
    windDirection: "ENE",
    windSpeedKt: 21,
    gustKt: 32,
    seasFt: 7,
    swellFt: 5,
    swellDirection: "E trade swell",
    swellPeriodSec: 9,
    rainChancePercent: 48,
    clouds: "mostly",
    advisory: "Passing showers and rough windward water",
    summary: "Breezy, showery, and exposed. Good local knowledge matters.",
    source: "Mock blend: NWS hourly, NOAA CWF, MFM",
    issuedAt,
  },
  {
    zoneId: "maui-county-windward-waters",
    period: "Tomorrow",
    windDirection: "ENE",
    windSpeedKt: 25,
    gustKt: 36,
    seasFt: 8,
    swellFt: 6,
    swellDirection: "E trade swell",
    swellPeriodSec: 8,
    rainChancePercent: 50,
    clouds: "mostly",
    advisory: "Rough windward waters",
    summary: "Maui County Windward Waters marine forecast data.",
    source: "Mock blend: NWS hourly, NOAA CWF, MFM",
    issuedAt,
  },
  {
    zoneId: "maui-county-windward-waters",
    period: "Day 3",
    windDirection: "E",
    windSpeedKt: 19,
    gustKt: 28,
    seasFt: 6,
    swellFt: 4,
    swellDirection: "E trade swell",
    swellPeriodSec: 10,
    rainChancePercent: 30,
    clouds: "partly",
    summary: "Maui County Windward Waters marine forecast data.",
    source: "Mock blend: NWS hourly, NOAA CWF, MFM",
    issuedAt,
  },
  {
    zoneId: "channels",
    period: "Today",
    windDirection: "ENE",
    windSpeedKt: 25,
    gustKt: 35,
    seasFt: 8,
    swellFt: 5,
    swellDirection: "E/NE wind swell",
    swellPeriodSec: 8,
    rainChancePercent: 34,
    clouds: "partly",
    advisory: "Accelerated channel trades",
    summary: "Channel wind is the limiter today; experienced crews only.",
    source: "Mock blend: NWS hourly, NOAA CWF, MFM",
    issuedAt,
  },
  {
    zoneId: "maui-county-windward-waters",
    period: "Today",
    windDirection: "ENE",
    windSpeedKt: 23,
    gustKt: 33,
    seasFt: 7,
    swellFt: 5,
    swellDirection: "E trade swell",
    swellPeriodSec: 9,
    rainChancePercent: 42,
    clouds: "mostly",
    advisory: "Small craft should monitor updates",
    summary: "Rougher windward waters with trade showers and short-period chop.",
    source: "Mock blend: NWS hourly, NOAA CWF, MFM",
    issuedAt,
  },
  {
    zoneId: "maui-county-leeward-waters",
    period: "Today",
    windDirection: "NE",
    windSpeedKt: 14,
    gustKt: 22,
    seasFt: 4,
    swellFt: 2,
    swellDirection: "S/SSW",
    swellPeriodSec: 12,
    rainChancePercent: 20,
    clouds: "partly",
    summary: "Maui County Leeward Waters marine forecast data.",
    source: "Mock blend: NWS hourly, NOAA CWF, MFM",
    issuedAt,
  },
  {
    zoneId: "maui-county-leeward-waters",
    period: "Tomorrow",
    windDirection: "NE",
    windSpeedKt: 17,
    gustKt: 25,
    seasFt: 5,
    swellFt: 3,
    swellDirection: "SSW",
    swellPeriodSec: 14,
    rainChancePercent: 24,
    clouds: "partly",
    summary: "Maui County Leeward Waters marine forecast data.",
    source: "Mock blend: NWS hourly, NOAA CWF, MFM",
    issuedAt,
  },
  {
    zoneId: "maui-county-leeward-waters",
    period: "Day 3",
    windDirection: "ENE",
    windSpeedKt: 13,
    gustKt: 19,
    seasFt: 3,
    swellFt: 3,
    swellDirection: "S",
    swellPeriodSec: 15,
    rainChancePercent: 18,
    clouds: "few",
    summary: "Maui County Leeward Waters marine forecast data.",
    source: "Mock blend: NWS hourly, NOAA CWF, MFM",
    issuedAt,
  },
];

const mockBuoy: BuoyObservation = {
  stationId: "51205",
  name: "Pauwela, Maui North Shore",
  latitude: 21.018,
  longitude: -156.426,
  observedAt: "2026-05-18T06:40:00-10:00",
  windDirectionDeg: 72,
  windSpeedKt: 20,
  gustKt: 28,
  waveHeightFt: 5.9,
  dominantPeriodSec: 10,
  waterTempF: 78,
  pressureMb: 1017.4,
  status: "data available",
  source: "Mock NDBC 51205",
};

const mockKahuluiHarborStation: BuoyObservation = {
  stationId: "KLIH1",
  name: "Kahului, Kahului Harbor, HI",
  latitude: 20.895,
  longitude: -156.469,
  observedAt: "2026-05-18T08:00:00-10:00",
  windDirectionDeg: 80,
  windSpeedKt: 20,
  gustKt: 26,
  waterTempF: 79.7,
  pressureMb: 1016.9,
  status: "data available",
  source: "NDBC KLIH1 / NOAA NOS station 1615680",
};

const mockOffshore51004: BuoyObservation = {
  stationId: "51004",
  name: "Southeast Hawaii offshore buoy",
  latitude: 17.504,
  longitude: -152.197,
  observedAt: "2026-05-17T11:40:00-10:00",
  windDirectionDeg: 80,
  windSpeedKt: 15.5,
  gustKt: 19.4,
  waveHeightFt: 8.5,
  dominantPeriodSec: 9,
  waterTempF: 78.4,
  pressureMb: 1015.6,
  status: "data available",
  source: "NDBC 51004",
};

const mockWhots51wh0: BuoyObservation = {
  stationId: "51WH0",
  name: "WHOTS offshore buoy",
  latitude: 22,
  longitude: -157,
  observedAt: "2026-05-18T06:30:00-10:00",
  windDirectionDeg: 90,
  windSpeedKt: 13.6,
  waterTempF: 76.5,
  status: "data available",
  source: "NDBC 51WH0",
};

const mockLanai51213: BuoyObservation = {
  stationId: "51213",
  name: "Kaumalapau Southwest, Lanai, HI",
  latitude: 20.75,
  longitude: -157.002,
  observedAt: "2026-05-17T08:56:00-10:00",
  waveHeightFt: 4.3,
  dominantPeriodSec: 15,
  waterTempF: 78.8,
  status: "data available",
  source: "NDBC 51213",
};

const mockHarborWinds: HarborWindObservation[] = [
  {
    id: "maalaea",
    name: "Maalaea Harbor",
    latitude: 20.7903,
    longitude: -156.5128,
    observedAt: "2026-05-18T08:00:00-10:00",
    windDirection: "NE",
    windDirectionDeg: 55,
    windSpeedKt: 15,
    gustKt: 22,
    rainChancePercent: 18,
    clouds: "few",
    status: "data available",
    source: "Mock NWS point + nearby marine blend",
  },
  {
    id: "mala-ramp",
    name: "Mala Ramp / Lahaina",
    latitude: 20.884,
    longitude: -156.684,
    observedAt: "2026-05-18T08:00:00-10:00",
    windDirection: "NE",
    windDirectionDeg: 48,
    windSpeedKt: 10,
    gustKt: 16,
    rainChancePercent: 15,
    clouds: "few",
    status: "data available",
    source: "Mock NWS point + nearby marine blend",
  },
  {
    id: "lahaina",
    name: "Lahaina Harbor",
    latitude: 20.872,
    longitude: -156.678,
    observedAt: "2026-05-18T08:00:00-10:00",
    windDirection: "NE",
    windDirectionDeg: 50,
    windSpeedKt: 11,
    gustKt: 17,
    rainChancePercent: 15,
    clouds: "few",
    status: "data available",
    source: "Mock NWS point + nearby marine blend",
  },
  {
    id: "kahului",
    name: "Kahului Harbor / KLIH1",
    latitude: 20.895,
    longitude: -156.469,
    observedAt: mockKahuluiHarborStation.observedAt,
    windDirection: "E",
    windDirectionDeg: mockKahuluiHarborStation.windDirectionDeg,
    windSpeedKt: mockKahuluiHarborStation.windSpeedKt,
    gustKt: mockKahuluiHarborStation.gustKt,
    rainChancePercent: 24,
    clouds: "partly",
    status: "data available",
    source: mockKahuluiHarborStation.source,
  },
];

const mockWarnings: MarineWarning[] = [
  {
    id: "mock-sca-windward",
    title: "Small Craft Advisory Watch",
    severity: "moderate",
    zones: ["channels", "maui-county-windward-waters", "windward-hana"],
    summary: "Trades and short-period seas are near advisory thresholds in exposed waters.",
    effectiveAt: issuedAt,
    expiresAt: "2026-05-18T18:00:00-10:00",
    source: "Mock NWS alerts",
  },
];

const mockTides: TideEvent[] = [
  {
    stationId: "1615680",
    stationName: "Kahului Harbor",
    time: "2026-05-18T07:18:00-10:00",
    type: "low",
    heightFt: 0.3,
    source: "Mock NOAA CO-OPS",
  },
  {
    stationId: "1615680",
    stationName: "Kahului Harbor",
    time: "2026-05-18T13:42:00-10:00",
    type: "high",
    heightFt: 1.8,
    source: "Mock NOAA CO-OPS",
  },
  {
    stationId: "1615680",
    stationName: "Kahului Harbor",
    time: "2026-05-18T19:56:00-10:00",
    type: "low",
    heightFt: 0.5,
    source: "Mock NOAA CO-OPS",
  },
];

const mockSurf: SurfForecast[] = [
  {
    shore: "north",
    area: "North Shore / Ho'okipa / Paia",
    today: "2-4 ft",
    tomorrow: "2-3 ft",
    day3: "2-4 ft",
    swellDirection: "NNW + easterly trade swell",
    swellPeriod: "medium-period NNW, short-period east",
    trend: "Small trade-mix with afternoon texture.",
    wind: "ENE trades building midday",
    notes: "Cleaner early, bumpier once wind fills in.",
    source: "Mock NWS SRF + buoy blend",
    issuedAt,
  },
  {
    shore: "west",
    area: "West Maui",
    today: "1-3 ft",
    tomorrow: "1-2 ft",
    day3: "1-3 ft",
    swellDirection: "NNW wrap",
    swellPeriod: "medium-period",
    trend: "Small with light wrap.",
    wind: "Protected early, light texture later",
    notes: "Mostly small, watch afternoon side-shore texture.",
    source: "Mock NWS SRF + buoy blend",
    issuedAt,
  },
  {
    shore: "south",
    area: "Kihei / Wailea / La Perouse",
    today: "1-2 ft",
    tomorrow: "1-3 ft",
    day3: "2-4 ft",
    swellDirection: "SSW + S",
    swellPeriod: "medium to long-period",
    trend: "Small south pulse, tide-sensitive.",
    wind: "Light early, Maalaea wind possible later",
    notes: "Small south swell building into Day 3. Lanai buoy 51213 shows SSW energy in the water.",
    source: "Mock NWS SRF + buoy blend",
    issuedAt,
  },
  {
    shore: "east",
    area: "Hana / Windward",
    today: "4-6 ft",
    tomorrow: "4-6 ft",
    day3: "3-5 ft",
    swellDirection: "E trade swell",
    swellPeriod: "short-period",
    trend: "Choppy trade-wind surf.",
    wind: "ENE trades and passing showers",
    notes: "More energy, less clean. Check rain bands.",
    source: "Mock NWS SRF + buoy blend",
    issuedAt,
  },
];

export async function generateMauiReport(): Promise<MauiDailyReport> {
  const officialMauiFads = createOfficialMauiFads(issuedAt);

  return {
    date: "Monday, May 18, 2026",
    headline: "Maui ocean conditions",
    humanSummary: "Explicit Maui wind, swell, seas, tide, rain, cloud, buoy, station, and source data.",
    zones: mauiZones,
    forecasts: mockForecasts,
    buoys: [mockBuoy, mockKahuluiHarborStation, mockOffshore51004, mockWhots51wh0, mockLanai51213],
    harborWinds: mockHarborWinds,
    fads: officialMauiFads,
    tides: mockTides,
    surf: mockSurf,
    warnings: mockWarnings,
    sourceTimestamps: [
      nwsSourceTimestamp,
      noaaMarineTextSourceTimestamp,
      noaaTidesSourceTimestamp,
      nwsSurfSourceTimestamp,
      hawaiiWeatherTodaySourceTimestamp,
      windytronSourceTimestamp,
      ndbcSourceTimestamp,
      pacioosSourceTimestamp,
      fadsSourceTimestamp,
      {
        source: "Maui report generator",
        status: "mock",
        updatedAt: issuedAt,
        note: "Mock data composer for explicit forecast blocks.",
      },
    ],
  };
}
